### ISSUE TITLE
Week1 Tasks checklist

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/animalsgonewild#2]
@nrao944 :
- [x] Create project structure for py package
- [x] name of repository: “Animals gone wild”
- [x] license(MIT license)

@zjr-mds :
- [x] CONTRIBUTOR sections in README
- [x] Code of Conduct
- [x] Edit CONTRIBUTING.md

@morganrosenberg50 :
edit README.md :
- [x] I. a high-level summary paragraph 
- [x] II. bullet list of 4 functions (each with 1-2 sentence of description)
- [x] III. brief statement of this package’s purpose

@Kylemaj :
- [x] team contract

Part 4: Function Documents (let’s create the issue page individually)
- [x] Animal classifier (@zjr-mds )
- [x] Animal subclassifier (1 of 3 ducks for example based on another feature of the text) (@morganrosenberg50 )
- [x] Word Cloud  (@nrao944)
- [x] Word replace (@Kylemaj)
