### ISSUE TITLE
week3 tasks checklist

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/animalsgonewild#36]
- [x] polish documentation and deployed by ReadTheDocs @Kylemaj 
- [x] actions workflows for continuous integration (ci) and continuous deployment (cd) @morganrosenberg50 

ACCOMPLISHMENT
- [x] GREEN RELEASE BUTTON !!!

submission:
- [x] 2 URLS: submit on Canvas with 1 link to the repo, and 1 link to the release page @nrao944
